version: '3.8'

services:
    app:
        build: .
        image: ngg/apiwbap:1.0
        ports:
            - "3000:3000"
        env_file: .env
        environment:
          - NODE_ENV=development
          - MONGODB_ATLAS_URI=${MONGODB_ATLAS_URI}
        volumes:
          - .:/usr/src/app
          - /usr/src/app/node_modules  # Prevent overwriting node_modules
          - /usr/src/app/dist         # Prevent overwriting compiled files
        restart: unless-stopped
        healthcheck:
          test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
          interval: 30s
          timeout: 10s
          retries: 3

  # For production, consider using Docker secrets
secrets:
   mongodb_uri:
      external: true

